### PR TITLE
Do not keep ACS data longer than necessary

### PR DESCRIPTION
**Pull request by zmbc**
### Description

- *Category*: performance
- *JIRA issue*: none
- *Research reference*: none

### Changes and notes

This should free up the memory (once it is garbage collected) after we are done with the ACS data, which is quite large.

### Verification and Testing

Integration tests passing.

### CODE REVIEW

**Comment by mattkappel** [comment]
Did you observe that garbage was collected? `mprof -CM simulate run ...` should produce a graph of usage over time if you're interested.

**Review by mattkappel — APPROVED** [review]

**Review by rmudambi — APPROVED** [review]

**Comment by zmbc** [comment]
>Did you observe that garbage was collected?

Good call -- this appears to be working (population 250k, keep in mind that the ACS data is also about 1/5th of the country):

image

**Comment by aflaxman** [comment]
Beka Stoerts’s recent PRL paper says they used a single machine with 2TB of memory.  Is 5G a big deal these days?

(and cool plot!)

**Comment by zmbc** [comment]
> Is 5G a big deal these days?

No; but, it's actually 25G once we include the whole country, and keeping it in memory means it will be _added_ to the slow accumulation over time in the right side of the plot, which I expect will scale with population size.

**Pull request merged**
